language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

# command to run tests and test coverage
addons:
  apt:
    packages:
      - python-coverage

script:
  - pytest --cov=picfixPy

after_sucess:
  - codecov
  
